### ISSUE TITLE
structure of PointOfInterest model

### ISSUE THREAD

**Issue by chicco785** [FIWARE/data-models#134]
Should be the PointOfInterest a basic Model, extended by all the other specific Models?

i.e. the entity stays a PointOfInterest for all submodels, but submodels have specific categories and introduce additional attributes.I find it more appropriate and suitable for generic queries. 

Also, for consistency, all scripts to generate data, should be in the "harvest" folder, like for WeatherObserved model.

**Comment by chicco785** [comment]
this looks to be the case for WeatherStation, but not for Beach and Museum

{
    "category": "WeatherStation",
    "location": {
      "type": "Point",
      "coordinates": [
        -7.684722222222222,
        43.78611111111111
      ]
    },
    "name": "Estaca de Bares",
    "postalAddress": {
      "addressCountry": "ES",
      "addressLocality": "Mañón",
      "addressRegion": "A Coruña"
    },
    "source": "http://aemet.es",
    "type": "PointOfInterest",
    "id": "WeatherStation-ES-1351"
}

**Comment by jmcanterafonseca** [comment]
we have not put code on the `harvest`folder because it is not a harvesting but an importation from a non public data source. 

With regards to the structure, there are two options make everything inherit from 'PointOfInterest' or the suggested approach which is have a reference `seeAlso`from a PointOfInterest entity to another specific entity which provides a concrete description of the place associated to the `PointOfInterest` which could be a `Beach` a `Museum` or similar.

**Comment by albertoabellagarcia** [comment]
this should be moved to https://github.com/smart-data-models
